--What is the average selling price of all the products?
select 
avg(sellingPrice) as avg_selling_price
from `e1.products`


--The finance team wants a summary of all payment transections
select 
 count(*) as no_of_payments,
 sum(Amount) as Total_payment_amt,
 avg (Amount) as avg_amt,
 min(Amount) as min_amt,
 max(Amount) as max_amt
from `e1.payments`


--Give me the count of the number of products withinin each category
select 
 CategoryID,
 count(*) as product_count
from `e1.products`
group by CategoryID


--How many units of each products have been sold?
select
 ProductID,
 sum(Quantity) as total_Quantity
from `e1.order_items`
group by ProductID


--What is the total sales value generated by each product?
select
 ProductID,
 sum(Total) as total_sales
from `e1.order_items`
group by ProductID


--what was the average selling price at which each product was sold?
select
 ProductID,
 avg(SellingPrice) as avg_selling_price
from `e1.order_items`
group by ProductID


--product sales summary--> for every product, what is statics summary?
select
 ProductID,
 sum(Total) as total_sales,
 round(avg(Total),2)as avg_sales,
 count(*) as count_sales,
 min(Total) as min_sales,
 max(Total) as max_sales,
from `e1.order_items`
group by ProductID


--for each customer, how many orders are there for each of their different order status?
select
 CustomerID,
 Status,
 count(*) as no_of_orders
from `e1.orders` 
group by CustomerID,Status

select
 CustomerID,
 Status,                        
 count(*) as no_of_orders
from `e1.orders`
group by Status, CustomerID


--How many inventory records are maintained for each warehouse?
select 
 WarehouseID,
 count(*) as no_of_records
from `e1.inventory`
group by WarehouseID


--How many orders are handled by each of the employee for each status?
select
 EmployeeID,
 Status,
 count(OrderID) as total_orders
from `e1.orders`
group by EmployeeID,Status


--How many produts in each category have an MRP above 20,000?
select
 CategoryID,
 count(ProductID) as no_of_products
from `e1.products`
where MRP > 20000
group by CategoryID


--What is the total quantity sold for each product when quantity is greater than 1?
select
ProductID,
sum(Quantity) as total_quantity
from `e1.order_items`
where Quantity > 1
group by ProductID


--What is the average payment for each payment method among sucessful payments?
select
 Method,
 round(avg(Amount),2) as avg_amt
from `e1.payments`
where status = "success"
group by Method










