"Show me the product name and the category name"
products --productName
linakge: categoryID
category --category Name

tableName.columnName

syntax:
select
from table1
join table2
on table1.key = table2.key


alter table `e1.categories`
rename column string_field_0 to categoryID


alter table `e1.categories`
rename column categoryID to categoryName


select
  p.ProductID,
  p.ProductName,
  c.categoryID,
  c.categoryName
from `e1.categories` as c
inner join `e1.products` as p
on c.categoryID=p.CategoryID 

--Display products belonging to the Electronics category.
select
  p.ProductID,
  p.ProductName,
  c.categoryID,
  c.categoryName
from `e1.products` as p
 inner join `e1.categories` as c
on p.CategoryID=c.categoryID
where c.categoryName="Electronics"


--Display products with their category names, sorted by MRP from highest to lowest.
select
  p.ProductID,
  c.categoryName,
  p.MRP
from `e1.products` as p
inner join `e1.categories` as c
on p.CategoryID = c.categoryID
order by p.MRP desc


--Display ProductName, CategoryName and discount amount.
select
  p.ProductName,
  c.categoryName,
  p.MRP-SellingPrice as discount_amount
from `e1.products` as p
inner join `e1.categories` as c
on c.categoryID=p.CategoryID


--Display each product along with its supplier name and supplier state.
select
  p.ProductName,
  s.SupplierName,
  s.state
from `e1.suppliers` as s
inner join `e1.products` as p
on p.SupplierID= s.SupplierID


--Display all Cancelled customer orders along with customer name and city.
select
  o.Status,
  c.Name,
  c.City
from `e1.customers` as c
inner join `e1.orders` as o
on o.CustomerID=c.CustomerID
where o.Status="Cancelled"

--Calculate total sales value for every order.
select
  o.OrderID,
  sum(oi.Total) as total_sales
from `e1.order_items` as oi
inner join `e1.orders` as o
on o.OrderID=oi.OrderID
group by o.OrderID


--Calculate total sales value generated by each customer.
1.customer name -> customer
2. linkage -> table: orders
customerid -> orders + customer
orderid -> orders + order_items
3.total sales -> order_items

select
c.CustomerID,
sum(oi.Total) as total_sales
from `e1.customers` as c
inner join `e1.orders` as o
on o.CustomerID=c.CustomerID
inner join `e1.order_items` as oi
on o.OrderID = oi.OrderID
group by c.CustomerID
order by total_sales desc

--Product-Wise sales with productName
select
 oi.ProductID,
 p.ProductName,
 sum(oi.Total) as total_sales
from `e1.products` as p
join `e1.order_items` as oi
on oi.ProductID=p.ProductID
group by oi.ProductID,p.ProductName
order by total_sales desc


--CategoryName-Wise total Sales
select
c.categoryName,
c.categoryID,
sum(oi.Total) as total_sales
from `e1.categories` as c
inner join `e1.products` as p
on c.categoryID = p.CategoryID
inner join `e1.order_items` as oi
on oi.ProductID = p.ProductID
group by c.categoryName,categoryID
order by total_sales desc


--Calculate total sales generated by products from each supplier
select
s.SupplierID,
sum(oi.Total) as total_sales
from `e1.suppliers` as s
inner join `e1.products` as p
on s.SupplierID = p.SupplierID
inner join `e1.order_items` as oi
on oi.ProductID = p.ProductID
group by s.SupplierID
order by total_sales desc



--Product-Wise sales with productName
select
 oi.ProductID,
 p.ProductName,
 sum(oi.Total) as total_sales
from `e1.products` as p
join `e1.order_items` as oi
on oi.ProductID=p.ProductID
group by oi.ProductID,p.ProductName
order by total_sales desc


--CategoryName-Wise total Sales
select
c.categoryName,
c.categoryID,
sum(oi.Total) as total_sales
from `e1.categories` as c
inner join `e1.products` as p
on c.categoryID = p.CategoryID
inner join `e1.order_items` as oi
on oi.ProductID = p.ProductID
group by c.categoryName,categoryID
order by total_sales desc


--Calculate total sales generated by products from each supplier
select
s.SupplierID,
sum(oi.Total) as total_sales
from `e1.suppliers` as s
inner join `e1.products` as p
on s.SupplierID = p.SupplierID
inner join `e1.order_items` as oi
on oi.ProductID = p.ProductID
group by s.SupplierID
order by total_sales desc



--Product-Wise sales with productName
select
 oi.ProductID,
 p.ProductName,
 sum(oi.Total) as total_sales
from `e1.products` as p
join `e1.order_items` as oi
on oi.ProductID=p.ProductID
group by oi.ProductID,p.ProductName
order by total_sales desc


--CategoryName-Wise total Sales
select
c.categoryName,
c.categoryID,
sum(oi.Total) as total_sales
from `e1.categories` as c
inner join `e1.products` as p
on c.categoryID = p.CategoryID
inner join `e1.order_items` as oi
on oi.ProductID = p.ProductID
group by c.categoryName,categoryID
order by total_sales desc


--Calculate total sales generated by products from each supplier
select
s.SupplierID,
sum(oi.Total) as total_sales
from `e1.suppliers` as s
inner join `e1.products` as p
on s.SupplierID = p.SupplierID
inner join `e1.order_items` as oi
on oi.ProductID = p.ProductID
group by s.SupplierID
order by total_sales desc

--Product-Wise sales with productName
select
 oi.ProductID,
 p.ProductName,
 sum(oi.Total) as total_sales
from e1.products as p
join e1.order_items as oi
on oi.ProductID=p.ProductID
group by oi.ProductID,p.ProductName
order by total_sales desc


--CategoryName-Wise total Sales
select
c.categoryName,
c.categoryID,
sum(oi.Total) as total_sales
from e1.categories as c
inner join e1.products as p
on c.categoryID = p.CategoryID
inner join e1.order_items as oi
on oi.ProductID = p.ProductID
group by c.categoryName,categoryID
order by total_sales desc


--Calculate total sales generated by products from each supplier
select
s.SupplierID,
sum(oi.Total) as total_sales
from e1.suppliers as s
inner join e1.products as p
on s.SupplierID = p.SupplierID
inner join e1.order_items as oi
on oi.ProductID = p.ProductID
group by s.SupplierID
order by total_sales desc







