--Product-Wise sales with productName
select
  p.ProductID,
  p.ProductName,
  sum(oi.Total) as total_sales
from `e1.products` as p
inner join `e1.order_items` as oi
on p.ProductID = oi.ProductID
group by p.ProductID,p.ProductName
order by total_sales desc


--CategoryName-Wise total Sales
select
  c.categoryID,
  c.categoryName,
  sum(oi.Total) as total_sales
from `e1.categories` as c
inner join `e1.products` as p
on c.categoryID = p.CategoryID
inner join `e1.order_items` as oi
on p.ProductID = oi.ProductID
group by c.categoryName,c.categoryID
order by total_sales desc


--Calculate total sales generated by products from each supplier.
select
  s.SupplierID,
  s.SupplierName,
  sum(oi.Total) as total_sales
from `e1.suppliers` as s
inner join `e1.products` as p
on p.SupplierID = s.SupplierID
inner join `e1.order_items` as oi
on p.ProductID = oi.ProductID
group by s.SupplierID,s.SupplierName
order by total_sales desc


--Display all products and any order-item sales associated with them.
select
  p.ProductID,
  p.ProductName,
  sum(oi.Total) as total_sales
from `e1.products` as p
inner join `e1.order_items` as oi
on p.ProductID = oi.ProductID
group by p.ProductID,p.ProductName
order by total_sales desc


--Find Products With No Sales
select
  p.ProductID,
  p.ProductName,
  sum(oi.Total) as sales
from `e1.products` as p
left join `e1.order_items` as oi
on p.ProductID = oi.ProductID
where oi.ProductID is null
group by p.ProductID,p.ProductName


--Customers who registered but have never placed an order.
select
  c.CustomerID,
  c.Name,
  o.CustomerID,
  o.OrderID
from `e1.customers` as c
left join `e1.orders` as o
on c.CustomerID = o.CustomerID
where o.OrderID is null


--For every customer, show the number of orders they have placed,including customers with zero orders.
select
  c.CustomerID,
  c.Name,
  count(o.OrderID) as no_of_orders
from `e1.customers` as c
left join `e1.orders` as o
on c.CustomerID = o.CustomerID
group by c.CustomerID,c.Name
order by no_of_orders asc



-- using right join
select
c.CustomerID,
c.Name,
count(o.OrderID) as no_of_orders
from `e1.orders` as o
right join `e1.customers` as c
on c.CustomerID = o.CustomerID
group by c.CustomerID,c.Name
order by no_of_orders asc


--For every customer, calculate:
--Customer ID
--Customer name
--Number of orders placed
--Total amount paid through successful payments only
--Display only customers whose successful payment amount is
--greater than ₹50,000.
--Sort customers from highest to lowest successful payment amount.

