--Product-Wise sales with productName
select
  p.ProductID,
  p.ProductName,
  sum(oi.Total) as total_sales
from `e1.products` as p
inner join `e1.order_items` as oi
on p.ProductID = oi.ProductID
group by p.ProductID,p.ProductName
order by total_sales desc


--CategoryName-Wise total Sales
select
  c.categoryID,
  c.categoryName,
  sum(oi.Total) as total_sales
from `e1.categories` as c
inner join `e1.products` as p
on c.categoryID = p.CategoryID
inner join `e1.order_items` as oi
on p.ProductID = oi.ProductID
group by c.categoryName,c.categoryID
order by total_sales desc


--Calculate total sales generated by products from each supplier.
select
  s.SupplierID,
  s.SupplierName,
  sum(oi.Total) as total_sales
from `e1.suppliers` as s
inner join `e1.products` as p
on p.SupplierID = s.SupplierID
inner join `e1.order_items` as oi
on p.ProductID = oi.ProductID
group by s.SupplierID,s.SupplierName
order by total_sales desc


--Display all products and any order-item sales associated with them.
select
  p.ProductID,
  p.ProductName,
  sum(oi.Total) as total_sales
from `e1.products` as p
inner join `e1.order_items` as oi
on p.ProductID = oi.ProductID
group by p.ProductID,p.ProductName
order by total_sales desc


--Find Products With No Sales
select
  p.ProductID,
  p.ProductName,
  sum(oi.Total) as sales
from `e1.products` as p
left join `e1.order_items` as oi
on p.ProductID = oi.ProductID
where oi.ProductID is null
group by p.ProductID,p.ProductName


--Customers who registered but have never placed an order.
select
  c.CustomerID,
  c.Name,
  o.CustomerID,
  o.OrderID
from `e1.customers` as c
left join `e1.orders` as o
on c.CustomerID = o.CustomerID
where o.OrderID is null


--For every customer, show the number of orders they have placed,including customers with zero orders.
select
  c.CustomerID,
  c.Name,
  count(o.OrderID) as no_of_orders
from `e1.customers` as c
left join `e1.orders` as o
on c.CustomerID = o.CustomerID
group by c.CustomerID,c.Name
order by no_of_orders asc



-- using right join
select
c.CustomerID,
c.Name,
count(o.OrderID) as no_of_orders
from `e1.orders` as o
right join `e1.customers` as c
on c.CustomerID = o.CustomerID
group by c.CustomerID,c.Name
order by no_of_orders asc


--For every customer, calculate:
--Customer ID
--Customer name
--Number of orders placed
--Total amount paid through successful payments only
--Display only customers whose successful payment amount is
--greater than ₹50,000.
--Sort customers from highest to lowest successful payment amount.







--For every customer, calculate:
--Customer ID
--Customer name
--Number of orders placed
--Total amount paid through successful payments only
--Display only customers whose successful payment amount is greater than ₹50,000.
--Sort customers from highest to lowest successful payment amount.

select
  c.CustomerID,
  c.Name,
  count(distinct o.OrderID) as no_of_orders,
  sum(p.Amount) as total_paid
from `e1.customers` as c
inner join `e1.orders` as o
  on c.CustomerID = o.CustomerID
inner join `e1.payments` as p
  on p.OrderID = o.OrderID
where p.Status = "success"
group by c.CustomerID,c.Name
having sum(p.Amount) > 50000
order by total_paid desc


--Find the top 10 products by total sales value.
--Display:
--ProductID --> product
--ProductName --> product
--CategoryName --> category
--SupplierName --> supplier
--Number of times the product appeared in order items -->order_items
--Total quantity sold--> order_items
--Total sales value --> order_items
--Average selling price --> order_items
--Only include products where the total sales value is greater than ₹1,00,000.

select
  p.ProductID,
  p.ProductName,
  c.categoryName,
  s.SupplierName,
  count(oi.OrderID) as no_of_prds,
  sum(oi.Quantity) as total_quantity,
  sum(oi.Total) as total_sales_value,
  avg(oi.SellingPrice) as avg_selling_price
from `e1.products` as p
inner join `e1.categories` as c
on p.CategoryID = c.categoryID
inner join `e1.suppliers` as s
on s.SupplierID = p.SupplierID
inner join `e1.order_items` as oi
 on oi.ProductID = p.ProductID
group by
  p.ProductID,
  p.ProductName,
  c.categoryName,
  s.SupplierName
having sum(oi.Total) > 100000
order by total_sales_value desc
limit 10


--Consider only products having an MRP greater than ₹20,000.
--For every category, calculate:
--CategoryID --> category
--CategoryName --> category
--Number of qualifying products --> products
--Average MRP of qualifying products --> products
--Maximum MRP --> products
--Minimum MRP --> products
--Display only categories having more than 2 qualifying products.
--Sort by average MRP from highest to lowest.

select
  c.categoryID,
  c.categoryName,
  count(p.ProductID) as no_of_products,
  round(avg(p.MRP),2) as avg_mrp,
  max(p.MRP) as max_mrp,
  min(p.MRP) as min_mrp
from `e1.products` as p
inner join `e1.categories` as c
 on p.CategoryID = c.categoryID
where MRP > 20000
group by 
c.categoryID,
c.categoryName
having count(p.ProductID) > 2
order by avg_mrp desc


--Find all customers who have never placed an order. --> order table -> null
--Display:
--CustomerID --> customer
--Customer name --> customer
--City --> customer
--Sort the result alphabetically by customer name.

select
c.CustomerID,
c.Name,
c.City,
o.OrderID
from `e1.customers` as c
left join `e1.orders` as o
on o.CustomerID = c.CustomerID
where OrderID is null
group by 
c.CustomerID,
c.Name,
c.City,
o.OrderID
order by c.Name


--For every supplier, calculate:
--SupplierID --> supplier
--SupplierName --> supplier
--Number of products supplied --> product
--Average MRP of their products --> product
--Total sales generated by their products --> order_items
--Total quantity sold --> order_items
--Include suppliers even if their products have never been sold.--> priority to suppliers
--For suppliers with no sales, display the sales and quantity as 0.
--Sort suppliers by total sales from highest to lowest.

select
  s.SupplierID,
  s.SupplierName,
  count(distinct p.ProductID) as no_of_products,
  avg(p.MRP) as avg_mrp,
  coalesce(sum(oi.Total),0) as total_sales,
  coalesce(sum(oi.Quantity),0) as total_qnts
from `e1.suppliers` as s
left join `e1.products` as p    
  on s.SupplierID = p.SupplierID
left join `e1.order_items` as oi
  on p.ProductID = oi.ProductID
group by
s.SupplierID,
s.SupplierName
order by total_sales desc




