--For every warehouse, calculate:
--WarehouseID -->warehouse
--Warehouse name --> warehouse
--Number of orders handled --> orders
--Total quantity of products sold --> order_items
--Total sales value --> order_items
-- importance -->warehouse table
--Include warehouses even if they have no orders.
--Display only warehouses where the total sales value is greater
--than ₹2,00,000. -->having

alter table `e1.warehouses`
rename column string_field_0 to WarehouseID

alter table `e1.warehouses`
rename column string_field_1 to WarehouseName

select
  w.WarehouseID,
  w.WarehouseName,
  count (distinct o.OrderID) as no_of_orders,
  coalesce(sum(oi.Quantity),0) as total_qnt,
  coalesce(sum(oi.Total),0) as total_sales
from `e1.warehouses` as w
left join `e1.orders` as o
  on o.WarehouseID = w.WarehouseID
left join `e1.order_items` as oi
  on oi.OrderID = o.OrderID
group by
w.WarehouseID,
w.WarehouseName
having total_sales > 200000
order by total_sales desc



--Calculate the total sales value generated by every customer.
--Then display only those customers whose total spending is
--greater than the average customer spending.
--Display:
--CustomerID --> customer
--Customer name --> customer
--Total spending --> order_items
--Sort from highest spending to lowest.

select 
  c.CustomerID,
  c.Name,
  sum(oi.Total) as total_sales
from `e1.customers` as c
inner join `e1.orders` as o
  on o.CustomerID = c.CustomerID
inner join `e1.order_items` as oi
  on oi.OrderID = o.OrderID
group by 
c.CustomerID,
c.Name
having total_sales > (select 
                     round(avg(total_sales),2)
                    from (select
                    o.CustomerID,
                    sum(oi.Total) as total_sales
                    from `e1.order_items` as oi
                    inner join `e1.orders` as o
                    on o.OrderID = oi.OrderID
                    group by o.CustomerID
                    ) 
                 )
order by total_sales desc


--For every product, calculate its total sales value.
--Display only products whose total sales value is greater than
--the average total sales value of products belonging to the same category.
--Display:
--ProductID --> product
--ProductName --> product
--CategoryName --> category
--TotalSales --> order_items
--Sort by total sales from highest to lowest.

select
  p.ProductID,
  p.ProductName,
  c.categoryName,
  sum(oi.Total) as total_sales
from `e1.products` as p
inner join `e1.categories` as c 
  on p.CategoryID = p.CategoryID
inner join `e1.order_items` as oi
  on oi.ProductID = p.ProductID
group by 
  p.ProductID,
  p.ProductName,
  p.CategoryID,
  c.categoryName
having total_sales > (select
  avg(total_sales) as avg_sales
  from(select 
       p1.ProductID,
       sum(oi.Total) as total_sales
     from `e1.products` as p1
     inner join `e1.order_items` as oi 
       on p1.ProductID = oi.ProductID
     where p1.CategoryID = p.CategoryID
     group by p1.ProductID))
order by total_sales desc



--For every order, calculate the total order value by adding the
--Total column from order_items.
--Then classify each order as:
--High Value → Total order value ≥ ₹50,000
--Medium Value → Total order value between ₹20,000 and ₹49,999
--Low Value → Total order value < ₹20,000
--Display:
--OrderID
--OrderDate
--CustomerName
--TotalOrderValue
--OrderCategory
--Show the highest-value orders first.


--case when statements
--if-elseif-else

syntax:
case
    when condition1 then result1
    when condition2 then result2
    when condition3 then result3
    else default_result
end


--categorise customers as 
--18-20: genz,
--21-40:adult,
--41 onward : senior_citizen

select
  CustomerID,
  Age,
  Name,
  case
    when Age >= 18 and Age <= 20 then "Genz"
    when Age >= 21 and Age <= 40 then "Adult"
    else "Senior_citizen"
  end as age_group  
from `e1.customers` as c


select
  CustomerID,
  Age,
  Name,
  case
    when Age >= 18 and Age <= 20 then "Genz"
    when Age <= 40 then "Adult"
    when age > 40  then "Senior_citizen"
  end as age_group  
from `e1.customers` as c


F --> Female
M  --> Male

